# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab19765e9e083380f926cf108943db1921a2bd4b98322f66163433d421408a44b85a08d101e03709a02dd48abe275d10658c8093b6c8bb866e5d57aaf49c54fc

test:
  secret_key_base: 01f098420030a00dfe2fb00b0e5509cb545baac982990658059006c8d5da621d090a3fe3957e34df48b9dead2eb984b660fbb575a9ee36ed87b82fd88a317e2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
